# Generated by Django 5.0.7 on 2024-07-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_category_language_book_category_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstract',
            options={'verbose_name': 'Avtoreferat', 'verbose_name_plural': 'Avtoreferatlar'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Kitob', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='discuss',
            options={'verbose_name': 'Muhokama', 'verbose_name_plural': 'Muhokamalar'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Til', 'verbose_name_plural': 'Tillar'},
        ),
        migrations.AlterModelOptions(
            name='magazine',
            options={'verbose_name': 'Jurnal', 'verbose_name_plural': 'Jurnallar'},
        ),
    ]
